#!/bin/bash

# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set +o xtrace
ip a
TEST_DIR=/tmp/results
MATRIX=testing/tests/test_tests.json
COMPLIANT_IMAGE="testrun/compliant"
TESTER="compliant_tester"

# Remove and recreate results directory
rm -rf $TEST_DIR/
mkdir -p $TEST_DIR

# Setup requirements
sudo apt-get update
sudo apt-get install -y openvswitch-common openvswitch-switch tcpdump jq moreutils coreutils isc-dhcp-client

# Setup device network
sudo ip link add dev xyz type dummy
sudo ip link add dev endev0a type veth peer name endev0b
sudo ip link set dev endev0a up
sudo ip link set dev endev0b up
sudo docker network remove endev0
sudo docker network create -d macvlan -o parent=endev0b endev0

# Start OVS
sudo /usr/share/openvswitch/scripts/ovs-ctl start

# Build the compliant test container 
sudo docker build ./testing/docker/ci_test_device1/compliant -t $COMPLIANT_IMAGE -f ./testing/docker/ci_test_device1/compliant/Dockerfile

# Copy configuration to testrun
sudo cp testing/tests/system.json local/system.json

# Copy device configs to testrun
sudo cp -r testing/device_configs/* local/devices

# Log file paths
testrun_log=$TEST_DIR/${TESTER}_testrun.log
device_log=$TEST_DIR/${TESTER}_device.log

# Extract details from JSON
image=$(jq -r .$TESTER.image $MATRIX)
ethmac=$(jq -r .$TESTER.ethmac $MATRIX)

# Start the testrun
echo Starting testrun
touch $testrun_log
sudo timeout 2400 bin/testrun --single-intf --no-ui > $testrun_log 2>&1 &
TPID=$!

# Time to wait for testrun to be ready
WAITING=750

for i in `seq 1 $WAITING`; do
tail -1 $testrun_log
    if [[ -n $(fgrep "Waiting for devices on the network" $testrun_log) ]]; then
        break
    fi

    if [[ ! -d /proc/$TPID ]]; then
        cat $testrun_log
        echo "Error encountered starting testrun"
        exit 1
    fi

    sleep 1
done

if [[ $i -eq $WAITING ]]; then
    cat $testrun_log
    echo "Failed after waiting $WAITING seconds for testrun to start"
    exit 1
fi

# Check if container is running before trying to stop and remove it
if sudo docker ps -a --format '{{.Names}}' | grep -Eq "^${TESTER}\$"; then
sudo docker stop $TESTER && sudo docker rm $TESTER
fi

echo Running container $image

# Run the test container
sudo docker run -d \
--network=endev0 \
--mac-address=$ethmac \
--cap-add=NET_ADMIN \
-v /tmp:/out \
--privileged \
--name=$TESTER \
$image

# Wait for test completion
WAITING=2400
for i in `seq 1 $WAITING`; do
tail -1 $testrun_log
    if [[ -n $(fgrep "All tests complete" $testrun_log) ]]; then
        sleep 10
        sudo kill -9 $TPID
    fi

    if [[ ! -d /proc/$TPID ]]; then
        break
    fi

    sleep 1
done

sudo docker logs $TESTER | cat 
sudo docker kill $TESTER && sudo docker rm $TESTER
echo Stopping container $TESTER

cp runtime/test/${ethmac//:/}/report.json $TEST_DIR/$TESTER.json
more $TEST_DIR/$TESTER.json | cat 
more $testrun_log | cat 

done

# Needs to be sudo because this invokes bin/testrun 
sudo venv/bin/python3 -m pytest -v testing/tests/test_tests.py

exit $?
